url: http://blog.jonfk.ca
title: "Jonfk's Blog"
author: Jonathan Fok kan
description: "Where I blog about things"

markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: []

gems:
  - jekyll-sitemap
  - jekyll-feed
