url: http://blog.jonfk.ca
title: "Jonfk's Blog"
author: Jonathan Fok kan
description: "Where I blog about things"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

gems:
  - jekyll-sitemap
  - jekyll-feed
