base_url = "https://www.jonfk.ca"
title = "Jonfk"
description = "jonfk's home on the web"
default_language = "en"

compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]

[markdown]
highlight_code = true
highlight_theme = "monokai"
insert_anchor_links = "heading"

[extra]
author = "Jonathan Fok kan"
